/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

using System;
using System.Collections.Generic;
using System.IO;
using LCM.LCM;
 
namespace mwt
{
    public sealed class dspl_cfg_t : LCM.LCM.LCMEncodable
    {
        public sbyte lout;
 
        public dspl_cfg_t()
        {
        }
 
        public static readonly ulong LCM_FINGERPRINT;
        public static readonly ulong LCM_FINGERPRINT_BASE = 0x90e9a182eec1a030L;
 
        static dspl_cfg_t()
        {
            LCM_FINGERPRINT = _hashRecursive(new List<String>());
        }
 
        public static ulong _hashRecursive(List<String> classes)
        {
            if (classes.Contains("mwt.dspl_cfg_t"))
                return 0L;
 
            classes.Add("mwt.dspl_cfg_t");
            ulong hash = LCM_FINGERPRINT_BASE
                ;
            classes.RemoveAt(classes.Count - 1);
            return (hash<<1) + ((hash>>63)&1);
        }
 
        public void Encode(LCMDataOutputStream outs)
        {
            outs.Write((long) LCM_FINGERPRINT);
            _encodeRecursive(outs);
        }
 
        public void _encodeRecursive(LCMDataOutputStream outs)
        {
            outs.Write(this.lout); 
 
        }
 
        public dspl_cfg_t(byte[] data) : this(new LCMDataInputStream(data))
        {
        }
 
        public dspl_cfg_t(LCMDataInputStream ins)
        {
            if ((ulong) ins.ReadInt64() != LCM_FINGERPRINT)
                throw new System.IO.IOException("LCM Decode error: bad fingerprint");
 
            _decodeRecursive(ins);
        }
 
        public static mwt.dspl_cfg_t _decodeRecursiveFactory(LCMDataInputStream ins)
        {
            mwt.dspl_cfg_t o = new mwt.dspl_cfg_t();
            o._decodeRecursive(ins);
            return o;
        }
 
        public void _decodeRecursive(LCMDataInputStream ins)
        {
            this.lout = ins.ReadSByte();
 
        }
 
        public mwt.dspl_cfg_t Copy()
        {
            mwt.dspl_cfg_t outobj = new mwt.dspl_cfg_t();
            outobj.lout = this.lout;
 
            return outobj;
        }
    }
}

