/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

using System;
using System.Collections.Generic;
using System.IO;
using LCM.LCM;
 
namespace mwt
{
    public sealed class filter_status_t : LCM.LCM.LCMEncodable
    {
        public double input;
        public double output;
        public double tau;
 
        public filter_status_t()
        {
        }
 
        public static readonly ulong LCM_FINGERPRINT;
        public static readonly ulong LCM_FINGERPRINT_BASE = 0x302fe57b7736ae94L;
 
        static filter_status_t()
        {
            LCM_FINGERPRINT = _hashRecursive(new List<String>());
        }
 
        public static ulong _hashRecursive(List<String> classes)
        {
            if (classes.Contains("mwt.filter_status_t"))
                return 0L;
 
            classes.Add("mwt.filter_status_t");
            ulong hash = LCM_FINGERPRINT_BASE
                ;
            classes.RemoveAt(classes.Count - 1);
            return (hash<<1) + ((hash>>63)&1);
        }
 
        public void Encode(LCMDataOutputStream outs)
        {
            outs.Write((long) LCM_FINGERPRINT);
            _encodeRecursive(outs);
        }
 
        public void _encodeRecursive(LCMDataOutputStream outs)
        {
            outs.Write(this.input); 
 
            outs.Write(this.output); 
 
            outs.Write(this.tau); 
 
        }
 
        public filter_status_t(byte[] data) : this(new LCMDataInputStream(data))
        {
        }
 
        public filter_status_t(LCMDataInputStream ins)
        {
            if ((ulong) ins.ReadInt64() != LCM_FINGERPRINT)
                throw new System.IO.IOException("LCM Decode error: bad fingerprint");
 
            _decodeRecursive(ins);
        }
 
        public static mwt.filter_status_t _decodeRecursiveFactory(LCMDataInputStream ins)
        {
            mwt.filter_status_t o = new mwt.filter_status_t();
            o._decodeRecursive(ins);
            return o;
        }
 
        public void _decodeRecursive(LCMDataInputStream ins)
        {
            this.input = ins.ReadDouble();
 
            this.output = ins.ReadDouble();
 
            this.tau = ins.ReadDouble();
 
        }
 
        public mwt.filter_status_t Copy()
        {
            mwt.filter_status_t outobj = new mwt.filter_status_t();
            outobj.input = this.input;
 
            outobj.output = this.output;
 
            outobj.tau = this.tau;
 
            return outobj;
        }
    }
}

