/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

using System;
using System.Collections.Generic;
using System.IO;
using LCM.LCM;
 
namespace mwt
{
    public sealed class gain_scale_status_t : LCM.LCM.LCMEncodable
    {
        public bool enabled;
        public double kp_in;
        public double ki_in;
        public double kd_in;
        public double kp_out;
        public double ki_out;
        public double kd_out;
 
        public gain_scale_status_t()
        {
        }
 
        public static readonly ulong LCM_FINGERPRINT;
        public static readonly ulong LCM_FINGERPRINT_BASE = 0x58056ad4bf4807c7L;
 
        static gain_scale_status_t()
        {
            LCM_FINGERPRINT = _hashRecursive(new List<String>());
        }
 
        public static ulong _hashRecursive(List<String> classes)
        {
            if (classes.Contains("mwt.gain_scale_status_t"))
                return 0L;
 
            classes.Add("mwt.gain_scale_status_t");
            ulong hash = LCM_FINGERPRINT_BASE
                ;
            classes.RemoveAt(classes.Count - 1);
            return (hash<<1) + ((hash>>63)&1);
        }
 
        public void Encode(LCMDataOutputStream outs)
        {
            outs.Write((long) LCM_FINGERPRINT);
            _encodeRecursive(outs);
        }
 
        public void _encodeRecursive(LCMDataOutputStream outs)
        {
            outs.Write(this.enabled); 
 
            outs.Write(this.kp_in); 
 
            outs.Write(this.ki_in); 
 
            outs.Write(this.kd_in); 
 
            outs.Write(this.kp_out); 
 
            outs.Write(this.ki_out); 
 
            outs.Write(this.kd_out); 
 
        }
 
        public gain_scale_status_t(byte[] data) : this(new LCMDataInputStream(data))
        {
        }
 
        public gain_scale_status_t(LCMDataInputStream ins)
        {
            if ((ulong) ins.ReadInt64() != LCM_FINGERPRINT)
                throw new System.IO.IOException("LCM Decode error: bad fingerprint");
 
            _decodeRecursive(ins);
        }
 
        public static mwt.gain_scale_status_t _decodeRecursiveFactory(LCMDataInputStream ins)
        {
            mwt.gain_scale_status_t o = new mwt.gain_scale_status_t();
            o._decodeRecursive(ins);
            return o;
        }
 
        public void _decodeRecursive(LCMDataInputStream ins)
        {
            this.enabled = ins.ReadBoolean();
 
            this.kp_in = ins.ReadDouble();
 
            this.ki_in = ins.ReadDouble();
 
            this.kd_in = ins.ReadDouble();
 
            this.kp_out = ins.ReadDouble();
 
            this.ki_out = ins.ReadDouble();
 
            this.kd_out = ins.ReadDouble();
 
        }
 
        public mwt.gain_scale_status_t Copy()
        {
            mwt.gain_scale_status_t outobj = new mwt.gain_scale_status_t();
            outobj.enabled = this.enabled;
 
            outobj.kp_in = this.kp_in;
 
            outobj.ki_in = this.ki_in;
 
            outobj.kd_in = this.kd_in;
 
            outobj.kp_out = this.kp_out;
 
            outobj.ki_out = this.ki_out;
 
            outobj.kd_out = this.kd_out;
 
            return outobj;
        }
    }
}

