/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

using System;
using System.Collections.Generic;
using System.IO;
using LCM.LCM;
 
namespace mwt
{
    public sealed class header_t : LCM.LCM.LCMEncodable
    {
        public String publisher;
        public double timestamp;
        public long sequence;
 
        public header_t()
        {
        }
 
        public static readonly ulong LCM_FINGERPRINT;
        public static readonly ulong LCM_FINGERPRINT_BASE = 0x628deda648a19ac5L;
 
        static header_t()
        {
            LCM_FINGERPRINT = _hashRecursive(new List<String>());
        }
 
        public static ulong _hashRecursive(List<String> classes)
        {
            if (classes.Contains("mwt.header_t"))
                return 0L;
 
            classes.Add("mwt.header_t");
            ulong hash = LCM_FINGERPRINT_BASE
                ;
            classes.RemoveAt(classes.Count - 1);
            return (hash<<1) + ((hash>>63)&1);
        }
 
        public void Encode(LCMDataOutputStream outs)
        {
            outs.Write((long) LCM_FINGERPRINT);
            _encodeRecursive(outs);
        }
 
        public void _encodeRecursive(LCMDataOutputStream outs)
        {
            byte[] __strbuf = null;
            __strbuf = System.Text.Encoding.GetEncoding("US-ASCII").GetBytes(this.publisher); outs.Write(__strbuf.Length+1); outs.Write(__strbuf, 0, __strbuf.Length); outs.Write((byte) 0); 
 
            outs.Write(this.timestamp); 
 
            outs.Write(this.sequence); 
 
        }
 
        public header_t(byte[] data) : this(new LCMDataInputStream(data))
        {
        }
 
        public header_t(LCMDataInputStream ins)
        {
            if ((ulong) ins.ReadInt64() != LCM_FINGERPRINT)
                throw new System.IO.IOException("LCM Decode error: bad fingerprint");
 
            _decodeRecursive(ins);
        }
 
        public static mwt.header_t _decodeRecursiveFactory(LCMDataInputStream ins)
        {
            mwt.header_t o = new mwt.header_t();
            o._decodeRecursive(ins);
            return o;
        }
 
        public void _decodeRecursive(LCMDataInputStream ins)
        {
            byte[] __strbuf = null;
            __strbuf = new byte[ins.ReadInt32()-1]; ins.ReadFully(__strbuf); ins.ReadByte(); this.publisher = System.Text.Encoding.GetEncoding("US-ASCII").GetString(__strbuf);
 
            this.timestamp = ins.ReadDouble();
 
            this.sequence = ins.ReadInt64();
 
        }
 
        public mwt.header_t Copy()
        {
            mwt.header_t outobj = new mwt.header_t();
            outobj.publisher = this.publisher;
 
            outobj.timestamp = this.timestamp;
 
            outobj.sequence = this.sequence;
 
            return outobj;
        }
    }
}

