/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

using System;
using System.Collections.Generic;
using System.IO;
using LCM.LCM;
 
namespace mwt
{
    public sealed class mini_rov_turns_t : LCM.LCM.LCMEncodable
    {
        public mwt.header_t header;
        public double turns;
 
        public mini_rov_turns_t()
        {
        }
 
        public static readonly ulong LCM_FINGERPRINT;
        public static readonly ulong LCM_FINGERPRINT_BASE = 0xc7bc4affe2d79aacL;
 
        static mini_rov_turns_t()
        {
            LCM_FINGERPRINT = _hashRecursive(new List<String>());
        }
 
        public static ulong _hashRecursive(List<String> classes)
        {
            if (classes.Contains("mwt.mini_rov_turns_t"))
                return 0L;
 
            classes.Add("mwt.mini_rov_turns_t");
            ulong hash = LCM_FINGERPRINT_BASE
                 + mwt.header_t._hashRecursive(classes)
                ;
            classes.RemoveAt(classes.Count - 1);
            return (hash<<1) + ((hash>>63)&1);
        }
 
        public void Encode(LCMDataOutputStream outs)
        {
            outs.Write((long) LCM_FINGERPRINT);
            _encodeRecursive(outs);
        }
 
        public void _encodeRecursive(LCMDataOutputStream outs)
        {
            this.header._encodeRecursive(outs); 
 
            outs.Write(this.turns); 
 
        }
 
        public mini_rov_turns_t(byte[] data) : this(new LCMDataInputStream(data))
        {
        }
 
        public mini_rov_turns_t(LCMDataInputStream ins)
        {
            if ((ulong) ins.ReadInt64() != LCM_FINGERPRINT)
                throw new System.IO.IOException("LCM Decode error: bad fingerprint");
 
            _decodeRecursive(ins);
        }
 
        public static mwt.mini_rov_turns_t _decodeRecursiveFactory(LCMDataInputStream ins)
        {
            mwt.mini_rov_turns_t o = new mwt.mini_rov_turns_t();
            o._decodeRecursive(ins);
            return o;
        }
 
        public void _decodeRecursive(LCMDataInputStream ins)
        {
            this.header = mwt.header_t._decodeRecursiveFactory(ins);
 
            this.turns = ins.ReadDouble();
 
        }
 
        public mwt.mini_rov_turns_t Copy()
        {
            mwt.mini_rov_turns_t outobj = new mwt.mini_rov_turns_t();
            outobj.header = this.header.Copy();
 
            outobj.turns = this.turns;
 
            return outobj;
        }
    }
}

