/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

using System;
using System.Collections.Generic;
using System.IO;
using LCM.LCM;
 
namespace mwt
{
    public sealed class mini_rov_rowe_dvl_t : LCM.LCM.LCMEncodable
    {
        public mwt.header_t header;
        public double ts_centi_sec;
        public double x_vel_mm_sec;
        public double y_vel_mm_sec;
        public double z_vel_mm_sec;
        public double altitude_mm;
 
        public mini_rov_rowe_dvl_t()
        {
        }
 
        public static readonly ulong LCM_FINGERPRINT;
        public static readonly ulong LCM_FINGERPRINT_BASE = 0x7beb3c36942d60b7L;
 
        static mini_rov_rowe_dvl_t()
        {
            LCM_FINGERPRINT = _hashRecursive(new List<String>());
        }
 
        public static ulong _hashRecursive(List<String> classes)
        {
            if (classes.Contains("mwt.mini_rov_rowe_dvl_t"))
                return 0L;
 
            classes.Add("mwt.mini_rov_rowe_dvl_t");
            ulong hash = LCM_FINGERPRINT_BASE
                 + mwt.header_t._hashRecursive(classes)
                ;
            classes.RemoveAt(classes.Count - 1);
            return (hash<<1) + ((hash>>63)&1);
        }
 
        public void Encode(LCMDataOutputStream outs)
        {
            outs.Write((long) LCM_FINGERPRINT);
            _encodeRecursive(outs);
        }
 
        public void _encodeRecursive(LCMDataOutputStream outs)
        {
            this.header._encodeRecursive(outs); 
 
            outs.Write(this.ts_centi_sec); 
 
            outs.Write(this.x_vel_mm_sec); 
 
            outs.Write(this.y_vel_mm_sec); 
 
            outs.Write(this.z_vel_mm_sec); 
 
            outs.Write(this.altitude_mm); 
 
        }
 
        public mini_rov_rowe_dvl_t(byte[] data) : this(new LCMDataInputStream(data))
        {
        }
 
        public mini_rov_rowe_dvl_t(LCMDataInputStream ins)
        {
            if ((ulong) ins.ReadInt64() != LCM_FINGERPRINT)
                throw new System.IO.IOException("LCM Decode error: bad fingerprint");
 
            _decodeRecursive(ins);
        }
 
        public static mwt.mini_rov_rowe_dvl_t _decodeRecursiveFactory(LCMDataInputStream ins)
        {
            mwt.mini_rov_rowe_dvl_t o = new mwt.mini_rov_rowe_dvl_t();
            o._decodeRecursive(ins);
            return o;
        }
 
        public void _decodeRecursive(LCMDataInputStream ins)
        {
            this.header = mwt.header_t._decodeRecursiveFactory(ins);
 
            this.ts_centi_sec = ins.ReadDouble();
 
            this.x_vel_mm_sec = ins.ReadDouble();
 
            this.y_vel_mm_sec = ins.ReadDouble();
 
            this.z_vel_mm_sec = ins.ReadDouble();
 
            this.altitude_mm = ins.ReadDouble();
 
        }
 
        public mwt.mini_rov_rowe_dvl_t Copy()
        {
            mwt.mini_rov_rowe_dvl_t outobj = new mwt.mini_rov_rowe_dvl_t();
            outobj.header = this.header.Copy();
 
            outobj.ts_centi_sec = this.ts_centi_sec;
 
            outobj.x_vel_mm_sec = this.x_vel_mm_sec;
 
            outobj.y_vel_mm_sec = this.y_vel_mm_sec;
 
            outobj.z_vel_mm_sec = this.z_vel_mm_sec;
 
            outobj.altitude_mm = this.altitude_mm;
 
            return outobj;
        }
    }
}

