/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

using System;
using System.Collections.Generic;
using System.IO;
using LCM.LCM;
 
namespace mwt
{
    public sealed class ml_cfg_t : LCM.LCM.LCMEncodable
    {
        public int score_threshold;
        public int box_deviation;
        public String model_name;
        public int framerate;
        public int exit_app;
 
        public ml_cfg_t()
        {
        }
 
        public static readonly ulong LCM_FINGERPRINT;
        public static readonly ulong LCM_FINGERPRINT_BASE = 0x7cd89df23c4535ffL;
 
        static ml_cfg_t()
        {
            LCM_FINGERPRINT = _hashRecursive(new List<String>());
        }
 
        public static ulong _hashRecursive(List<String> classes)
        {
            if (classes.Contains("mwt.ml_cfg_t"))
                return 0L;
 
            classes.Add("mwt.ml_cfg_t");
            ulong hash = LCM_FINGERPRINT_BASE
                ;
            classes.RemoveAt(classes.Count - 1);
            return (hash<<1) + ((hash>>63)&1);
        }
 
        public void Encode(LCMDataOutputStream outs)
        {
            outs.Write((long) LCM_FINGERPRINT);
            _encodeRecursive(outs);
        }
 
        public void _encodeRecursive(LCMDataOutputStream outs)
        {
            byte[] __strbuf = null;
            outs.Write(this.score_threshold); 
 
            outs.Write(this.box_deviation); 
 
            __strbuf = System.Text.Encoding.GetEncoding("US-ASCII").GetBytes(this.model_name); outs.Write(__strbuf.Length+1); outs.Write(__strbuf, 0, __strbuf.Length); outs.Write((byte) 0); 
 
            outs.Write(this.framerate); 
 
            outs.Write(this.exit_app); 
 
        }
 
        public ml_cfg_t(byte[] data) : this(new LCMDataInputStream(data))
        {
        }
 
        public ml_cfg_t(LCMDataInputStream ins)
        {
            if ((ulong) ins.ReadInt64() != LCM_FINGERPRINT)
                throw new System.IO.IOException("LCM Decode error: bad fingerprint");
 
            _decodeRecursive(ins);
        }
 
        public static mwt.ml_cfg_t _decodeRecursiveFactory(LCMDataInputStream ins)
        {
            mwt.ml_cfg_t o = new mwt.ml_cfg_t();
            o._decodeRecursive(ins);
            return o;
        }
 
        public void _decodeRecursive(LCMDataInputStream ins)
        {
            byte[] __strbuf = null;
            this.score_threshold = ins.ReadInt32();
 
            this.box_deviation = ins.ReadInt32();
 
            __strbuf = new byte[ins.ReadInt32()-1]; ins.ReadFully(__strbuf); ins.ReadByte(); this.model_name = System.Text.Encoding.GetEncoding("US-ASCII").GetString(__strbuf);
 
            this.framerate = ins.ReadInt32();
 
            this.exit_app = ins.ReadInt32();
 
        }
 
        public mwt.ml_cfg_t Copy()
        {
            mwt.ml_cfg_t outobj = new mwt.ml_cfg_t();
            outobj.score_threshold = this.score_threshold;
 
            outobj.box_deviation = this.box_deviation;
 
            outobj.model_name = this.model_name;
 
            outobj.framerate = this.framerate;
 
            outobj.exit_app = this.exit_app;
 
            return outobj;
        }
    }
}

