/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

using System;
using System.Collections.Generic;
using System.IO;
using LCM.LCM;
 
namespace mwt
{
    public sealed class position_t : LCM.LCM.LCMEncodable
    {
        public mwt.header_t header;
        public double latitude_deg;
        public double longitude_deg;
        public double altitude_m;
        public mwt.gps_status_t gps_status;
 
        public position_t()
        {
        }
 
        public static readonly ulong LCM_FINGERPRINT;
        public static readonly ulong LCM_FINGERPRINT_BASE = 0x97f9057a4b8d28f7L;
 
        static position_t()
        {
            LCM_FINGERPRINT = _hashRecursive(new List<String>());
        }
 
        public static ulong _hashRecursive(List<String> classes)
        {
            if (classes.Contains("mwt.position_t"))
                return 0L;
 
            classes.Add("mwt.position_t");
            ulong hash = LCM_FINGERPRINT_BASE
                 + mwt.header_t._hashRecursive(classes)
                 + mwt.gps_status_t._hashRecursive(classes)
                ;
            classes.RemoveAt(classes.Count - 1);
            return (hash<<1) + ((hash>>63)&1);
        }
 
        public void Encode(LCMDataOutputStream outs)
        {
            outs.Write((long) LCM_FINGERPRINT);
            _encodeRecursive(outs);
        }
 
        public void _encodeRecursive(LCMDataOutputStream outs)
        {
            this.header._encodeRecursive(outs); 
 
            outs.Write(this.latitude_deg); 
 
            outs.Write(this.longitude_deg); 
 
            outs.Write(this.altitude_m); 
 
            this.gps_status._encodeRecursive(outs); 
 
        }
 
        public position_t(byte[] data) : this(new LCMDataInputStream(data))
        {
        }
 
        public position_t(LCMDataInputStream ins)
        {
            if ((ulong) ins.ReadInt64() != LCM_FINGERPRINT)
                throw new System.IO.IOException("LCM Decode error: bad fingerprint");
 
            _decodeRecursive(ins);
        }
 
        public static mwt.position_t _decodeRecursiveFactory(LCMDataInputStream ins)
        {
            mwt.position_t o = new mwt.position_t();
            o._decodeRecursive(ins);
            return o;
        }
 
        public void _decodeRecursive(LCMDataInputStream ins)
        {
            this.header = mwt.header_t._decodeRecursiveFactory(ins);
 
            this.latitude_deg = ins.ReadDouble();
 
            this.longitude_deg = ins.ReadDouble();
 
            this.altitude_m = ins.ReadDouble();
 
            this.gps_status = mwt.gps_status_t._decodeRecursiveFactory(ins);
 
        }
 
        public mwt.position_t Copy()
        {
            mwt.position_t outobj = new mwt.position_t();
            outobj.header = this.header.Copy();
 
            outobj.latitude_deg = this.latitude_deg;
 
            outobj.longitude_deg = this.longitude_deg;
 
            outobj.altitude_m = this.altitude_m;
 
            outobj.gps_status = this.gps_status.Copy();
 
            return outobj;
        }
    }
}

