/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

using System;
using System.Collections.Generic;
using System.IO;
using LCM.LCM;
 
namespace mwt
{
    public sealed class stereo_bounding_box_t : LCM.LCM.LCMEncodable
    {
        public String publisher;
        public mwt.bounding_box_list_t left_boxes;
        public mwt.bounding_box_list_t right_boxes;
 
        public stereo_bounding_box_t()
        {
        }
 
        public static readonly ulong LCM_FINGERPRINT;
        public static readonly ulong LCM_FINGERPRINT_BASE = 0x469f948d1ed6a0f1L;
 
        static stereo_bounding_box_t()
        {
            LCM_FINGERPRINT = _hashRecursive(new List<String>());
        }
 
        public static ulong _hashRecursive(List<String> classes)
        {
            if (classes.Contains("mwt.stereo_bounding_box_t"))
                return 0L;
 
            classes.Add("mwt.stereo_bounding_box_t");
            ulong hash = LCM_FINGERPRINT_BASE
                 + mwt.bounding_box_list_t._hashRecursive(classes)
                 + mwt.bounding_box_list_t._hashRecursive(classes)
                ;
            classes.RemoveAt(classes.Count - 1);
            return (hash<<1) + ((hash>>63)&1);
        }
 
        public void Encode(LCMDataOutputStream outs)
        {
            outs.Write((long) LCM_FINGERPRINT);
            _encodeRecursive(outs);
        }
 
        public void _encodeRecursive(LCMDataOutputStream outs)
        {
            byte[] __strbuf = null;
            __strbuf = System.Text.Encoding.GetEncoding("US-ASCII").GetBytes(this.publisher); outs.Write(__strbuf.Length+1); outs.Write(__strbuf, 0, __strbuf.Length); outs.Write((byte) 0); 
 
            this.left_boxes._encodeRecursive(outs); 
 
            this.right_boxes._encodeRecursive(outs); 
 
        }
 
        public stereo_bounding_box_t(byte[] data) : this(new LCMDataInputStream(data))
        {
        }
 
        public stereo_bounding_box_t(LCMDataInputStream ins)
        {
            if ((ulong) ins.ReadInt64() != LCM_FINGERPRINT)
                throw new System.IO.IOException("LCM Decode error: bad fingerprint");
 
            _decodeRecursive(ins);
        }
 
        public static mwt.stereo_bounding_box_t _decodeRecursiveFactory(LCMDataInputStream ins)
        {
            mwt.stereo_bounding_box_t o = new mwt.stereo_bounding_box_t();
            o._decodeRecursive(ins);
            return o;
        }
 
        public void _decodeRecursive(LCMDataInputStream ins)
        {
            byte[] __strbuf = null;
            __strbuf = new byte[ins.ReadInt32()-1]; ins.ReadFully(__strbuf); ins.ReadByte(); this.publisher = System.Text.Encoding.GetEncoding("US-ASCII").GetString(__strbuf);
 
            this.left_boxes = mwt.bounding_box_list_t._decodeRecursiveFactory(ins);
 
            this.right_boxes = mwt.bounding_box_list_t._decodeRecursiveFactory(ins);
 
        }
 
        public mwt.stereo_bounding_box_t Copy()
        {
            mwt.stereo_bounding_box_t outobj = new mwt.stereo_bounding_box_t();
            outobj.publisher = this.publisher;
 
            outobj.left_boxes = this.left_boxes.Copy();
 
            outobj.right_boxes = this.right_boxes.Copy();
 
            return outobj;
        }
    }
}

