/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

using System;
using System.Collections.Generic;
using System.IO;
using LCM.LCM;
 
namespace mwt
{
    public sealed class turns_t : LCM.LCM.LCMEncodable
    {
        public double turns;
 
        public turns_t()
        {
        }
 
        public static readonly ulong LCM_FINGERPRINT;
        public static readonly ulong LCM_FINGERPRINT_BASE = 0x4cab85a1b2ae8a48L;
 
        static turns_t()
        {
            LCM_FINGERPRINT = _hashRecursive(new List<String>());
        }
 
        public static ulong _hashRecursive(List<String> classes)
        {
            if (classes.Contains("mwt.turns_t"))
                return 0L;
 
            classes.Add("mwt.turns_t");
            ulong hash = LCM_FINGERPRINT_BASE
                ;
            classes.RemoveAt(classes.Count - 1);
            return (hash<<1) + ((hash>>63)&1);
        }
 
        public void Encode(LCMDataOutputStream outs)
        {
            outs.Write((long) LCM_FINGERPRINT);
            _encodeRecursive(outs);
        }
 
        public void _encodeRecursive(LCMDataOutputStream outs)
        {
            outs.Write(this.turns); 
 
        }
 
        public turns_t(byte[] data) : this(new LCMDataInputStream(data))
        {
        }
 
        public turns_t(LCMDataInputStream ins)
        {
            if ((ulong) ins.ReadInt64() != LCM_FINGERPRINT)
                throw new System.IO.IOException("LCM Decode error: bad fingerprint");
 
            _decodeRecursive(ins);
        }
 
        public static mwt.turns_t _decodeRecursiveFactory(LCMDataInputStream ins)
        {
            mwt.turns_t o = new mwt.turns_t();
            o._decodeRecursive(ins);
            return o;
        }
 
        public void _decodeRecursive(LCMDataInputStream ins)
        {
            this.turns = ins.ReadDouble();
 
        }
 
        public mwt.turns_t Copy()
        {
            mwt.turns_t outobj = new mwt.turns_t();
            outobj.turns = this.turns;
 
            return outobj;
        }
    }
}

