/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

using System;
using System.Collections.Generic;
using System.IO;
using LCM.LCM;
 
namespace mwt
{
    public sealed class vehicle_cmd_t : LCM.LCM.LCMEncodable
    {
        public mwt.header_t header;
        public double x;
        public double y;
        public double z;
        public double phi;
        public double theta;
        public double psi;
 
        public vehicle_cmd_t()
        {
        }
 
        public static readonly ulong LCM_FINGERPRINT;
        public static readonly ulong LCM_FINGERPRINT_BASE = 0xba86a0c54fd80a1fL;
 
        static vehicle_cmd_t()
        {
            LCM_FINGERPRINT = _hashRecursive(new List<String>());
        }
 
        public static ulong _hashRecursive(List<String> classes)
        {
            if (classes.Contains("mwt.vehicle_cmd_t"))
                return 0L;
 
            classes.Add("mwt.vehicle_cmd_t");
            ulong hash = LCM_FINGERPRINT_BASE
                 + mwt.header_t._hashRecursive(classes)
                ;
            classes.RemoveAt(classes.Count - 1);
            return (hash<<1) + ((hash>>63)&1);
        }
 
        public void Encode(LCMDataOutputStream outs)
        {
            outs.Write((long) LCM_FINGERPRINT);
            _encodeRecursive(outs);
        }
 
        public void _encodeRecursive(LCMDataOutputStream outs)
        {
            this.header._encodeRecursive(outs); 
 
            outs.Write(this.x); 
 
            outs.Write(this.y); 
 
            outs.Write(this.z); 
 
            outs.Write(this.phi); 
 
            outs.Write(this.theta); 
 
            outs.Write(this.psi); 
 
        }
 
        public vehicle_cmd_t(byte[] data) : this(new LCMDataInputStream(data))
        {
        }
 
        public vehicle_cmd_t(LCMDataInputStream ins)
        {
            if ((ulong) ins.ReadInt64() != LCM_FINGERPRINT)
                throw new System.IO.IOException("LCM Decode error: bad fingerprint");
 
            _decodeRecursive(ins);
        }
 
        public static mwt.vehicle_cmd_t _decodeRecursiveFactory(LCMDataInputStream ins)
        {
            mwt.vehicle_cmd_t o = new mwt.vehicle_cmd_t();
            o._decodeRecursive(ins);
            return o;
        }
 
        public void _decodeRecursive(LCMDataInputStream ins)
        {
            this.header = mwt.header_t._decodeRecursiveFactory(ins);
 
            this.x = ins.ReadDouble();
 
            this.y = ins.ReadDouble();
 
            this.z = ins.ReadDouble();
 
            this.phi = ins.ReadDouble();
 
            this.theta = ins.ReadDouble();
 
            this.psi = ins.ReadDouble();
 
        }
 
        public mwt.vehicle_cmd_t Copy()
        {
            mwt.vehicle_cmd_t outobj = new mwt.vehicle_cmd_t();
            outobj.header = this.header.Copy();
 
            outobj.x = this.x;
 
            outobj.y = this.y;
 
            outobj.z = this.z;
 
            outobj.phi = this.phi;
 
            outobj.theta = this.theta;
 
            outobj.psi = this.psi;
 
            return outobj;
        }
    }
}

